f=open("File2.txt","w")
f.write("Yes I agree, he is a good person")
f.close()
f=open("File2.txt","a")
f.write("I hope you are also one\n")
f.close()
f=open("File2.txt","r")
print(f.read())
f.close()
f=open("File3.txt","a")
a=f.write("I hope you are also one\n")
print(a)
f.close()